### PR TITLE
python: poetry => uv port

### PR DESCRIPTION
**Pull request by reyammer**
This is an attempt to port the magika python module from `poetry` to `uv`.

`uv` seems to be using more standard pyproject.toml, and this should allow for easier integration with maturin (useful to package the magika rust binary within the python package).

Related: #631.

### CODE REVIEW

**Comment by reyammer** [comment]
@ia0: I think I'm done porting the python module from poetry to uv, can you give it a try updating the build system to maturin and see what happens?

@invernizzi: it seems that js tests currently fail; my understanding is that this is due to js codebase using the old model, which doesn't support some of the new content types (e.g., csv vs. tsv), so I've manually disabled the js-test workflow (https://github.com/google/magika/actions/workflows/js-test.yml) for the moment.

**Comment by reyammer** [comment]
For some reasons, the wrong version of numpy is installed when testing on python 3.8, and it leads to problems (see failed python - test workflow).

Details: when using python 3.8, the resolver should pick numpy 1.24.x, as specified https://github.com/google/magika/pull/663/files#diff-1a45bd938160f7761769e7b6fbc819d1cc7f84ce37f1a6a23ef83cc4e214abc8R15-R17. `uv.lock` also shows something similar. Unclear what's going on at the moment.

**Comment by ia0** [comment]
> @ia0: I think I'm done porting the python module from poetry to uv, can you give it a try updating the build system to maturin and see what happens?

It installs the dependencies (so that's already something) and theoretically magika too, but when I try `import magika` it doesn't find it.

```shell
% pip install magika-0.6.0.dev0-py3-none-linux_x86_64.whl
[...]
Successfully installed certifi-2024.8.30 charset-normalizer-3.3.2 click-8.1.7 coloredlogs-15.0.1 flatbuffers-24.3.25 humanfriendly-10.0 idna-3.8 magika-0.6.0.dev0 mpmath-1.3.0 numpy-2.1.0 onnxruntime-1.19.0 packaging-24.1 protobuf-5.28.0 python-dotenv-1.0.1 requests-2.32.3 sympy-1.13.2 urllib3-2.2.2
% python -c 'import magika'
[...]
ModuleNotFoundError: No module named 'magika'
```

**Comment by reyammer** [comment]
I had the same problem but I thought I fixed it in a newer version of .toml. Did you use the latest version of this PR?

**Comment by ia0** [comment]
> I had the same problem but I thought I fixed it in a newer version of .toml. Did you use the latest version of this PR?

Yes

**Comment by ia0** [comment]
Ok, after some more try-hard I managed to get it working. I've updated #564 to reflect that (it's now based on this PR, only the last commit is the real part of the PR). Here are the steps I took (from a clean clone of #564):

```
cd python
maturin build --release --out ../dist
cd ../dist
( python3 -m venv venv && venv/bin/pip install *.whl && venv/bin/magika --version && venv/bin/python3 -c 'import magika; print(magika.__version__)' )
```

I've also checked that the Maturin workflow produces a working wheel for linux: https://github.com/google/magika/actions/runs/10807633796. I downloaded the file, unzipped it, and run the last command above.

**Comment by reyammer** [comment]
Great, merged!

**Pull request merged**
