### PR TITLE
Updated-removal_mime_type Column

### PR DESCRIPTION
**Pull request by devilkadabra69**

### CODE REVIEW

**Review by reyammer — CHANGES_REQUESTED** [review]
we need to remove line 438 as well. Can you take care of this and then test it? I would expect the current PR to crash / show bad output?

**Comment by devilkadabra69** [comment]
can you just clearify :- other than line 438 where can it all be present because i was going through mime_type variable is present all over the code can you explain a bit

**Comment by reyammer** [comment]
I think it's OK to delete only that line. we don't want to print the mime type if we remove the mime type header from the column.

**Comment by devilkadabra69** [comment]
can you check the commit i have applied the necessary changes in the line 438

**Comment by reyammer** [comment]
Hello, sorry I've just merged #250 and I thought it was your initial PR. Thanks anyways and sorry!

**Comment by devilkadabra69** [comment]
no issues
its ok

**Pull request closed without merging**
