### PR TITLE
Release Rust crates

### PR DESCRIPTION
**Pull request by ia0**

### CODE REVIEW

**Review by reyammer — APPROVED** [review]

**Comment by ia0** [comment]
Need to fix MacOS.

**Comment by ia0** [comment]
MacOS "fix" coming in #719. Not sure what's the default in ONNX, but seems like we need to set some value.

**Comment by reyammer** [comment]
Note that the checks didn't pick up yet the new gh actions workflow that actually builds & test the package. Can we re-trigger all the workflows?

**Comment by ia0** [comment]
> Note that the checks didn't pick up yet the new gh actions workflow that actually builds & test the package. Can we re-trigger all the workflows?

The new workflow doesn't trigger when only rust files are touched, so it's working as intended. Why do you want the workflow to run? Maybe removing the paths restriction would be better?

**Comment by reyammer** [comment]
good catch; I thought it was just stale. I just updated the e2e test workflow to trigger also for rust/** modifications. Now it's running the checks again, and the build package is triggered, seems to work.

**Comment by ia0** [comment]
> good catch; I thought it was just stale. I just updated the e2e test workflow to trigger also for rust/** modifications. Now it's running the checks again, and the build package is triggered, seems to work.

Sounds good. I'll fix the problem in a different PR (to keep this PR small). It's a bug in the recent nightly https://github.com/rust-lang/rust-clippy/issues/13458

**Comment by ia0** [comment]
This is tagged as [rust-v0.1.0-rc.1](https://github.com/google/magika/releases/tag/rust-v0.1.0-rc.1) and published as [magika](https://crates.io/crates/magika/0.1.0-rc.1) and [magika-cli](https://crates.io/crates/magika-cli/0.1.0-rc.1). Because it's a pre-release, the version must be explicitly specified:

| Crate | Command to use or install |
| --- | --- |
| Library | `cargo add magika@=0.1.0-rc.1` |
| CLI | `cargo install --locked magika-cli@0.1.0-rc.1` |

**Pull request merged**
