### PR TITLE
Removed MIME Type Column from supported  list

### PR DESCRIPTION
**Pull request by devilkadabra69**
new colums are ->Index, Content Type Label ,Description

### CODE REVIEW

**Comment by nhonx** [comment]
We also need to remove the Column from here as well:
https://github.com/google/magika/blob/a9d3904fbe1523c740ecb20ebf0e742e4acf5892/python/magika/cli/magika.py#L432
It's shown when user use `magika --list-output-content-types`

**Comment by reyammer** [comment]
Thanks for the PR folks! The issue I've created was more of a "think about it" rather than "let's do it for sure" :-) but I still think it's a good idea. Maybe we should add a short discussion at the beginning or end of the table to justify this / point whoever sees the table to the discussion on output format. I need to think a bit about this...

**Comment by devilkadabra69** [comment]
i guess i missed headers part ! i'll fix it quickly

**Comment by reyammer** [comment]
Thanks!

**Pull request merged**
